name: messenger_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  auto_route: ^7.8.3
  bloc_concurrency: ^0.2.2
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.9.1

  faker: ^2.1.0
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  firebase_storage: ^11.2.6
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.1
  flutter_localizations:
    sdk: flutter
  form_validator: ^2.1.1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  google_fonts: ^6.0.0
  google_sign_in: ^6.1.5
  hydrated_bloc: ^9.1.2
  image_picker: ^1.0.4
  injectable: ^2.3.0
  intl: any
  json_annotation: ^4.8.1
  path_provider: ^2.1.1
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  auto_route_generator: ^7.3.1
  injectable_generator: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
